# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: "Release Megatron-Bridge"

on:
  workflow_dispatch:
    inputs:
      release-ref:
        description: Ref (SHA or branch name) to release
        required: true
        type: string
      dry-run:
        description: Do not publish a wheel and GitHub release.
        required: true
        default: true
        type: boolean
      create-gh-release:
        description: Create a GitHub release
        required: true
        default: true
        type: boolean
      version-bump-branch:
        description: Branch for version bump
        required: true
        type: string
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: write # To read repository content
  pull-requests: write # To create PRs

jobs:
  release:
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_release_library.yml@v0.54.3
    with:
      release-ref: ${{ inputs.release-ref || github.sha }}
      python-package: megatron.bridge
      library-name: Megatron-Bridge
      dry-run: ${{ inputs.dry-run || false }}
      version-bump-branch: ${{ inputs.version-bump-branch || github.ref_name }}
      create-gh-release: ${{ inputs.create-gh-release || true }}
      packaging: uv
      has-src-dir: true
      skip-test-wheel: true
      custom-container: nvcr.io/nvidia/pytorch:25.05-py3
      runner: linux-amd64-cpu16
      no-build-isolation: true
      app-id: ${{ vars.BOT_ID }}
    secrets:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      SLACK_WEBHOOK_ADMIN: ${{ secrets.SLACK_WEBHOOK_ADMIN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_ENDPOINT }}
      PAT: ${{ secrets.PAT }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PWD: ${{ secrets.SSH_PWD }}
      BOT_KEY: ${{ secrets.BOT_KEY }}
